# Generated by Django 3.2.12 on 2022-02-21 23:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostname',
            name='addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), null=True, size=None),
        ),
    ]
